#pragma once

#define SPLIT_LAYER_STATE_ENABLE
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TERM 220

#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_RIVERFLOW

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_ON false
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

