#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,               KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
        KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B,               KC_J, KC_L, KC_U, KC_Y, KC_LT, KC_DEL, 
        KC_LSFT, KC_A, KC_R, KC_S, KC_T, KC_G,              KC_M, KC_N, KC_E, KC_I, KC_O, KC_PIPE, 
        KC_LCTL, KC_Z, KC_X, KC_C, KC_D, KC_V,              KC_NO, KC_NO, KC_K, KC_H, KC_COMM, KC_DOT, 
        KC_AMPR, KC_SLSH, KC_NO, KC_NO, KC_LGUI, KC_LALT,   KC_SPC, KC_ENT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),

    [1] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_LT, KC_GT, KC_BSLS, KC_PLUS,       KC_CIRC, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_NO, 
        KC_NO, KC_EXLM, KC_SLSH, KC_RBRC, KC_RPRN, KC_NUHS, KC_PIPE, KC_GT, KC_ASTR, KC_LPRN, KC_PERC, KC_NO, 
        KC_NO, KC_NO, KC_AMPR, KC_RCBR, KC_GRV, KC_NO,      KC_NO, KC_NO, KC_TILD, KC_DLR, KC_LCBR, KC_RCBR, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

    [2] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_P7, KC_P8, KC_P9, KC_PMNS, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_P4, KC_P5, KC_P6, KC_PPLS, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_P0, KC_NO, KC_NO, KC_NO),

    [3] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, KC_NO, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, 
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,           KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

#ifdef ENCODER_ENABLE

bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
	} else if (index == 1) {
        if (clockwise) {
            tap_code(KC_PGDN);
        } else {
            tap_code(KC_PGUP);
        }
    }
    return true;
}

#endif

#ifdef OLED_ENABLE

static void render_logo(void) {
    static const char PROGMEM raw_logo[] = {
        0,  0,192,192,240,240,240,240,240,240,240,243,243,243,241,241,241,243,243,243,243,231,230,206,156, 24, 56, 16,128,128,  0,  0,  0,  7,  7,  1,255,255,255,255,255,255,255,  3,  3,  3,  3,  3,  3,  3,  3,  7,  7, 31,255,255,255,255,254,248,  1,  7,255,252, 63,252,224,128,255,255,255,255,255,255,255,128,128,128,128,128,128,192,192,192,224,248,254,255,255,255,127, 63,128,224,255, 63,  0,  1,  3,  3, 15, 31, 31, 31, 31, 31, 31, 31, 31,159,159,159,159,159,223,207,207,239,103,119, 59, 25, 28, 14,  7,  3,  0,  0,
    };
    oled_write_raw_P(raw_logo, sizeof(raw_logo));
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_270;
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        render_logo();
        oled_set_cursor(0, 5);
        // print_status_narrow();
    } else {
        render_logo();
    }
    return false;
}

#endif


