/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#include <stdio.h>
#include "keymap_german.h"
#include "sendstring_german.h"
#include "raw_hid.h"
#include "color.h"

#include QMK_KEYBOARD_H


enum sofle_layers {
    _DEFAULTS = 0,
    _QWERTZ = 0,
    _SYMBOLS,
    _NUMPAD,
    _ARROWS,
    _SETTINGS
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
    * QWERTZ
    * .-----------------------------------------------.                    .-----------------------------------------------.
    * |  ESC  | (F)1  | (F)2  | (F)3  | (F)4  | (F)5  |                    | (F)6  | (F)7  | (F)8  | (F)9  | (F1)0 | BSPC/F12 |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |       |   Q   |   W   |   E   |   R   |   T   |                    |   Z   |   U   |   I   |   O   |   P   |   Ü   |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Tab  |   A   |   S   |   D   |   F   |   G   |                    |   H   |   J   |   K   |   L   |   Ö   |   Ä   |
    * |-------+-------+-------+-------+-------+-------|-------.    .-------|-------+-------+-------+-------+-------+-------|
    * | Shift |   Y   |   X   |   C   |   V   |   B   |  MUTE |    |       |   N   |   M   |   ,   |   .   |   /   |   ß   |
    * '-----------------------------------------------|-------|    |-------|-----------------------------------------------'
    *                 |       |  WIN  |  ALT  |  NUM  | Space |    | Enter | SYMBL |  NUM  | ALTGR | SETTI |
    *                 |       |       |       |       |  CTL  /    \ SHIFT |       |       |       |       |
    *                 \--------------------------------------/      \--------------------------------------/
    */
    [_QWERTZ] = LAYOUT(
    //,------------------------------------------------.                    ,---------------------------------------------------.
        KC_ESC, LT(0,DE_1), LT(0,DE_2), LT(0,DE_3), LT(0,DE_4), LT(0,DE_5), LT(0,DE_6), LT(0,DE_7), LT(0,DE_8), LT(0,DE_9), LT(0,DE_0), LT(0,KC_BSPC),
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_NO, DE_Q,   DE_W,   DE_E,    DE_R,   DE_T,                         DE_Z,  DE_U,   DE_I,   DE_O,   DE_P,  DE_UDIA,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TAB, DE_A,   DE_S,   DE_D,    DE_F,   DE_G,                         DE_H,  DE_J,   DE_K,   DE_L,  DE_ODIA, DE_ADIA,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
        KC_LSFT, DE_Y,  DE_X,   DE_C,    DE_V,   DE_B,  KC_MUTE,     KC_NO,    DE_N,  DE_M,  DE_COMM, DE_DOT, DE_SLSH, DE_SS,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
                    KC_LCTL, KC_LGUI, KC_LALT, MO(2), LCTL_T(KC_SPC), LSFT_T(KC_ENT), MO(1), MO(3), KC_RALT, MO(4)
    //            \--------+--------+--------+---------+-------|   |--------+---------+--------+---------+-------/
    ),

    /*
    * Symbols
    * .-----------------------------------------------.                    .-----------------------------------------------.
    * |   ^   |   1   |   2   |   3   |   4   |   5   |                    |   6   |   7   |   8   |   9   |   0   | Bspc  |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Esc  |   '   |   <   |   >   |   "   |  -_   |                    |       |   &   |   [   |   ]   |   %   |       |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Tab  |   !   |   -   |   +   |   =   |   #   |                    |   |   |   :   |   (   |   )   |   ?   |       |
    * |-------+-------+-------+-------+-------+-------|-------.    .-------|-------+-------+-------+-------+-------+-------|
    * | Shift |   ^   |   /   |   *   |   \   |       |  MUTE |    |       |   ~   |   $   |   {   |   }   |   @   |       |
    * '-----------------------------------------------|-------|    |-------|-----------------------------------------------'
    *                 |       |  WIN  |  ALT  |  NUM  | Space |    | Enter | SYMBL | ALTGR |       | SETTI |
    *                 |       |       |       |       |       /    \       |       |       |       |       |
    *                 \--------------------------------------/      \--------------------------------------/
    */
    [_SYMBOLS] = LAYOUT(
    //,------------------------------------------------.                    ,---------------------------------------------------.
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,               KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, DE_QUOT, DE_LABK, DE_RABK, DE_DQUO, DE_MINS,                   KC_NO, DE_AMPR, DE_LBRC, DE_RBRC, DE_PERC, KC_NO,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, DE_EXLM, DE_MINS, DE_PLUS, DE_EQL, DE_HASH,                DE_PIPE, DE_COLN, DE_LPRN, DE_RPRN, DE_QUES, KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
        KC_LSFT, DE_CIRC, DE_SLSH, DE_ASTR, DE_BSLS, KC_NO, KC_TRNS, KC_NO, DE_TILD, DE_DLR,  DE_LCBR, DE_RCBR, DE_AT, KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    //            \--------+--------+--------+---------+-------|   |--------+---------+--------+---------+-------/
    ),

    /*
    * Numpad
    * .-----------------------------------------------.                    .-----------------------------------------------.
    * |   ^   |       |       |       |       |       |                    |       |       |       |       |       | Bspc  |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Esc  |       |       |       |       |       |                    |       |   7   |   8   |   9   |       |       |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Tab  |       |       |       |       |       |                    |       |   4   |   5   |   6   |       |       |
    * |-------+-------+-------+-------+-------+-------|-------.    .-------|-------+-------+-------+-------+-------+-------|
    * | Shift |       |       |       |       |       |  MUTE |    |       |   0   |   1   |   2   |   3   |       |       |
    * '-----------------------------------------------|-------|    |-------|-----------------------------------------------'
    *                 |       |  WIN  |  ALT  |  NUM  | Space |    | Enter | SYMBL | ALTGR |       | Bspc  |
    *                 |       |       |       |       |       /    \       |       |       |       |       |
    *                 \--------------------------------------/      \--------------------------------------/
    */

    [_NUMPAD] = LAYOUT(
    //,------------------------------------------------.                    ,---------------------------------------------------.
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_TRNS,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_P7,   KC_P8,   KC_P9,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_P4,   KC_P5,   KC_P6,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
        KC_LSFT, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO, KC_TRNS,     KC_NO, KC_P0,   KC_P1,   KC_P2,   KC_P3,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    //            \--------+--------+--------+---------+-------|   |--------+---------+--------+---------+-------/
    ),

    /*
    * Arrow
    * .-----------------------------------------------.                    .-----------------------------------------------.
    * |   ^   |       |       |       |       |       |                    |       |       |       |       |       | Bspc  |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Esc  |       |       |       |       |       |                    |       |       |       |       |       |       |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Tab  |       |       |       |       |       |                    |  LFT  | DOWN  |   UP  |  RGHT |       |       |
    * |-------+-------+-------+-------+-------+-------|-------.    .-------|-------+-------+-------+-------+-------+-------|
    * | Shift |       |       |       |       |       |  MUTE |    |       |       |       |       |       |       |       |
    * '-----------------------------------------------|-------|    |-------|-----------------------------------------------'
    *                 |       |  WIN  |  ALT  |  NUM  | Space |    | Enter | SYMBL | ALTGR |       | Bspc  |
    *                 |       |       |       |       |       /    \       |       |       |       |       |
    *                 \--------------------------------------/      \--------------------------------------/
    */
    [_ARROWS] = LAYOUT(
    //,------------------------------------------------.                    ,---------------------------------------------------.
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_NO,   KC_NO,  KC_NO,   KC_NO,  KC_TRNS,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_NO,   KC_NO,  KC_NO,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_LEFT, KC_DOWN, KC_UP,  KC_RIGHT, KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
        KC_LSFT, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO, KC_TRNS,     KC_NO, KC_NO,   KC_NO,   KC_NO,  KC_NO,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    //            \--------+--------+--------+---------+-------|   |--------+---------+--------+---------+-------/
    ),

    /*
    * SETTINGS
    * .-----------------------------------------------.                    .-----------------------------------------------.
    * |  RST  |       |       |       |       | EECLR |                    |       |       |       |       |       | Bspc  |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |  Esc  |       |       |       |       |       |                    |       |       |       |       |       |       |
    * |-------+-------+-------+-------+-------+-------|                    |-------+-------+-------+-------+-------+-------|
    * |       |       |       |       |       |       |                    |       |       |       |       |       |       |
    * |-------+-------+-------+-------+-------+-------|-------.    .-------|-------+-------+-------+-------+-------+-------|
    * |       |       |       |       |       |       |  MUTE |    |       |       |       |       |       |       |       |
    * '-----------------------------------------------|-------|    |-------|-----------------------------------------------'
    *                 |       |       |       |       | Space |    | Enter | RGB_T | RGB_U | RGB_D |       |
    *                 |       |       |       |       |       /    \       |       |       |       |       |
    *                 \--------------------------------------/      \--------------------------------------/
    */
    [_SETTINGS] = LAYOUT(
    //,------------------------------------------------.                    ,---------------------------------------------------.
        QK_BOOT, KC_NO,  KC_NO,  KC_NO,  KC_NO,  EE_CLR,                    RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO,  KC_TRNS,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_TRNS, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                     RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|                   |--------+-------+--------+--------+--------+---------|
        KC_NO, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                       KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
        KC_NO, KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO, KC_TRNS,     KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_NO,
    //|------+-------+--------+--------+--------+------|  ===  |   |  ===  |--------+-------+--------+--------+--------+---------|
                    KC_NO,  KC_NO,  KC_NO,  KC_NO, KC_TRNS,     KC_TRNS, RGB_TOG, RGB_MOD, RGB_RMOD, KC_NO
    //            \--------+--------+--------+---------+-------|   |--------+---------+--------+---------+-------/
    )
};


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    uint8_t msg[32];
    memset(msg, 0, 32);
    msg[0] = record->event.key.row;
    msg[1] = record->event.key.col;
    msg[2] = record->event.pressed;
    raw_hid_send(msg, 32);
    

    switch (keycode) {
        case LT(0, DE_1):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F1);
                return false;
            }
            return true;
        case LT(0, DE_2):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F2);
                return false;
            }
            return true;
        case LT(0, DE_3):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F3);
                return false;
            }
            return true;
        case LT(0, DE_4):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F4);
                return false;
            }
            return true;
        case LT(0, DE_5):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F5);
                return false;
            }
            return true;
        case LT(0, DE_6):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F6);
                return false;
            }
            return true;
        case LT(0, DE_7):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F7);
                return false;
            }
            return true;
        case LT(0, DE_8):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F8);
                return false;
            }
            return true;
        case LT(0, DE_9):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F9);
                return false;
            }
            return true;
        case LT(0, DE_0):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F10);
                return false;
            }
            return true;
        // case LT(0, DE_11): <--- Define key
        //     if (!record->tap.count && record->event.pressed) {
        //         tap_code16(KC_F1);
        //         return false;
        //     }
        //     return true;
        case LT(0, KC_BSPC):
            if (!record->tap.count && record->event.pressed) {
                tap_code16(KC_F12);
                return false;
            }
            return true;
    }
    return true;
};


#ifdef ENCODER_ENABLE

bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
	} else if (index == 1) {
        if (clockwise) {
            tap_code(KC_PGDN);
        } else {
            tap_code(KC_PGUP);
        }
    }
    return true;
}

#endif

#ifdef OLED_ENABLE

static void render_logo(void) {
    static const char PROGMEM raw_logo[] = {
        0,  0,192,192,240,240,240,240,240,240,240,243,243,243,241,241,241,243,243,243,243,231,230,206,156, 24, 56, 16,128,128,  0,  0,  0,  7,  7,  1,255,255,255,255,255,255,255,  3,  3,  3,  3,  3,  3,  3,  3,  7,  7, 31,255,255,255,255,254,248,  1,  7,255,252, 63,252,224,128,255,255,255,255,255,255,255,128,128,128,128,128,128,192,192,192,224,248,254,255,255,255,127, 63,128,224,255, 63,  0,  1,  3,  3, 15, 31, 31, 31, 31, 31, 31, 31, 31,159,159,159,159,159,223,207,207,239,103,119, 59, 25, 28, 14,  7,  3,  0,  0,
    };
    oled_write_raw_P(raw_logo, sizeof(raw_logo));
}


static void print_status_narrow(void) {
    switch (get_highest_layer(default_layer_state)) {
        case _QWERTZ:
            oled_write(PSTR("QWERT"), false);
            break;
        default:
            oled_write_ln_P(PSTR("Undef"), false);
    }
    oled_write_P(PSTR("\n\n"), false);
    // Print current layer
    oled_write_ln_P(PSTR("LAYER"), false);
    switch (get_highest_layer(layer_state)) {
        case _QWERTZ:
            oled_write_P(PSTR("Base\n"), false);
            break;
        case _SYMBOLS:
            oled_write_P(PSTR("Symbl\n"), false);
            break;
        case _NUMPAD:
            oled_write_P(PSTR("Nmpd\n"), false);
            break;
        case _ARROWS:
            oled_write_P(PSTR("Arrw\n"), false);
            break;
        case _SETTINGS:
            oled_write_P(PSTR("Sett\n"), false);
            break;
        default:
            oled_write_ln_P(PSTR("Undef"), false);
    }
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_270;
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        render_logo();
        oled_set_cursor(0, 5);
        print_status_narrow();
    } else {
        render_logo();
    }
    return false;
}

#endif

#ifdef RGB_MATRIX_ENABLE

bool rgb_matrix_indicators_kb(void) {
    if (!rgb_matrix_indicators_user()) {
        return false;
    }

    switch (get_highest_layer(layer_state)) {
        case _QWERTZ:
            rgb_matrix_set_color(0, 5, 40, 5);
            rgb_matrix_set_color(36, 5, 40, 5);
            break;
        case _SYMBOLS:
            rgb_matrix_set_color(0, 5, 75, 90);
            rgb_matrix_set_color(36, 5, 75, 90);
            break;
        case _NUMPAD:
            rgb_matrix_set_color(0, 90, 45, 5);
            rgb_matrix_set_color(36, 90, 45, 5);
            break;
        case _ARROWS:
            rgb_matrix_set_color(0, 85, 90, 5);
            rgb_matrix_set_color(36, 85, 90, 5);
            break;
        case _SETTINGS:
            rgb_matrix_set_color(0, 60, 5, 90);
            rgb_matrix_set_color(36, 60, 5, 90);
            break;
        default:
            rgb_matrix_set_color(0, 90, 10, 10);
            rgb_matrix_set_color(36, 90, 10, 10);
    }
    return true;
}

bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    HSV hsv = (HSV){ 130, 90, 65 };

    switch (get_highest_layer(layer_state)) {
        case _QWERTZ:
            hsv = (HSV){ 0, 0, 50 };
            break;
        case _SYMBOLS:
            hsv = (HSV){ 0, 90, 50 };
            break;
        case _NUMPAD:
            hsv = (HSV){ 210, 90, 50 };
            break;
        case _ARROWS:
            hsv = (HSV){ 35, 90, 50 };
            break;
        case _SETTINGS:
            hsv = (HSV){ 60, 90, 50 };
            break;
        default:
            hsv = (HSV){ 0, 90, 50 };
            break;
    }

    if (hsv.v > rgb_matrix_get_val()) {
        hsv.v = rgb_matrix_get_val();
    }

    RGB rgb = hsv_to_rgb(hsv);
    rgb_matrix_set_color(0, rgb.r, rgb.g, rgb.b);
    rgb_matrix_set_color(36, rgb.r, rgb.g, rgb.b);

    return false;
}

#endif
